import pygame
pygame.font.init()
FONT = pygame.font.SysFont('comicsans', 20)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREY = (100, 100, 100)
W = H = 600
OUTER_PADDING = 10
INNER_PADDING = 5
SYMBOL_PADDING = 8
BIG_SPAN = (W - 2*OUTER_PADDING) // 3
SMALL_SPAN = (BIG_SPAN - 2*INNER_PADDING) // 3
VERTICAL_RECTS = []
HORIZONTAL_RECTS = []
VRECTS = []
HRECTS = []
for i in range(1, 3):
    VERTICAL_RECT = pygame.Rect(OUTER_PADDING+i*BIG_SPAN-3, OUTER_PADDING, 6, H-2*OUTER_PADDING)
    VERTICAL_RECTS.append(VERTICAL_RECT)
    HORIZONTAL_RECT = pygame.Rect(OUTER_PADDING, OUTER_PADDING+i*BIG_SPAN-3, W-2*OUTER_PADDING, 6)
    HORIZONTAL_RECTS.append(HORIZONTAL_RECT)
for i in range(3):
    for j in range(1,7):
        if j  < 3:
            VRECT = pygame.Rect(OUTER_PADDING + INNER_PADDING + SMALL_SPAN * j -2, OUTER_PADDING + INNER_PADDING + BIG_SPAN * i, 4, BIG_SPAN - 2 * INNER_PADDING)
            HRECT = pygame.Rect(OUTER_PADDING + INNER_PADDING + BIG_SPAN * i, OUTER_PADDING + INNER_PADDING + SMALL_SPAN * j -2, BIG_SPAN - 2 * INNER_PADDING, 4 )
            VRECTS.append(VRECT)
            HRECTS.append(HRECT)
        elif j > 4:
            VRECT = pygame.Rect(OUTER_PADDING + INNER_PADDING + SMALL_SPAN * j + 4 * INNER_PADDING + 2 *SMALL_SPAN -2, OUTER_PADDING + INNER_PADDING + BIG_SPAN * i, 4, BIG_SPAN - 2 * INNER_PADDING)
            HRECT = pygame.Rect(OUTER_PADDING + INNER_PADDING + BIG_SPAN * i, OUTER_PADDING + INNER_PADDING + SMALL_SPAN * j + 4 * INNER_PADDING + 2 * SMALL_SPAN -2, BIG_SPAN - 2 * INNER_PADDING, 4 )
            HRECTS.append(HRECT)
            VRECTS.append(VRECT)
        else:
            VRECT = pygame.Rect(OUTER_PADDING + INNER_PADDING + SMALL_SPAN * j + 2 * INNER_PADDING + SMALL_SPAN -2, OUTER_PADDING + INNER_PADDING + BIG_SPAN * i, 4, BIG_SPAN - 2 * INNER_PADDING)
            HRECT = pygame.Rect(OUTER_PADDING + INNER_PADDING + BIG_SPAN * i, OUTER_PADDING + INNER_PADDING + SMALL_SPAN * j + 2 * INNER_PADDING + SMALL_SPAN -2, BIG_SPAN - 2 * INNER_PADDING, 4 )
            VRECTS.append(VRECT)
            HRECTS.append(HRECT)

rect1 = pygame.Rect(OUTER_PADDING + BIG_SPAN - 3, OUTER_PADDING, 6, BIG_SPAN)
rect2 = pygame.Rect(OUTER_PADDING, OUTER_PADDING + BIG_SPAN - 3, BIG_SPAN, 6)
rect3 = pygame.Rect(OUTER_PADDING + BIG_SPAN, OUTER_PADDING + BIG_SPAN - 3, BIG_SPAN, 6)
rect4 = pygame.Rect(OUTER_PADDING + 2* BIG_SPAN -3, OUTER_PADDING, 6, BIG_SPAN)
rect5 = pygame.Rect(OUTER_PADDING + 2* BIG_SPAN , OUTER_PADDING + BIG_SPAN - 3, BIG_SPAN, 6)
rect6 = pygame.Rect(OUTER_PADDING + BIG_SPAN - 3 , OUTER_PADDING + BIG_SPAN, 6, BIG_SPAN)
rect7 = pygame.Rect(OUTER_PADDING , OUTER_PADDING + 2*BIG_SPAN-6, BIG_SPAN, 6)
rect8 = pygame.Rect(OUTER_PADDING + BIG_SPAN , OUTER_PADDING + 2*BIG_SPAN-3, BIG_SPAN, 6)
rect9 = pygame.Rect(OUTER_PADDING + 2*BIG_SPAN - 3 , OUTER_PADDING + BIG_SPAN, 6, BIG_SPAN)
rect10 = pygame.Rect(OUTER_PADDING + 2*BIG_SPAN , OUTER_PADDING + 2*BIG_SPAN-3, BIG_SPAN, 6)
rect11 = pygame.Rect(OUTER_PADDING + BIG_SPAN - 3 , OUTER_PADDING + 2*BIG_SPAN, 6, BIG_SPAN)
rect12 = pygame.Rect(OUTER_PADDING + 2*BIG_SPAN - 3 , OUTER_PADDING + 2*BIG_SPAN, 6, BIG_SPAN)
